// <auto-generated />
using BlazorIncrementalApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorIncrementalApp.Migrations
{
    [DbContext(typeof(OrderDbContext))]
    [Migration("20251127094257_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Buttons", b =>
                {
                    b.Property<int>("ButtonsID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ButtonsID"));

                    b.Property<bool>("AutoClickerUnlocked")
                        .HasColumnType("bit");

                    b.Property<bool>("CriticalGainUnlocked")
                        .HasColumnType("bit");

                    b.Property<bool>("HighPointBtnUnlocked")
                        .HasColumnType("bit");

                    b.Property<bool>("MidPointBtnUnlocked")
                        .HasColumnType("bit");

                    b.HasKey("ButtonsID");

                    b.ToTable("Buttons");
                });

            modelBuilder.Entity("MindoorOres", b =>
                {
                    b.Property<int>("MindoorOresID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MindoorOresID"));

                    b.Property<int>("IronOre")
                        .HasColumnType("int");

                    b.Property<bool>("IronOreUnlocked")
                        .HasColumnType("bit");

                    b.HasKey("MindoorOresID");

                    b.ToTable("MindoorOres");
                });

            modelBuilder.Entity("MoonPoints", b =>
                {
                    b.Property<int>("MoonPointsID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MoonPointsID"));

                    b.Property<bool>("MindoorUnlocked")
                        .HasColumnType("bit");

                    b.Property<decimal>("MoonPoint")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("MoonUnlocked")
                        .HasColumnType("bit");

                    b.Property<bool>("PlanetsUnlocked")
                        .HasColumnType("bit");

                    b.Property<decimal>("TotalMindoorMultiplier")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalVenusMultiplier")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("VenusUnlocked")
                        .HasColumnType("bit");

                    b.HasKey("MoonPointsID");

                    b.ToTable("MoonPoints");
                });

            modelBuilder.Entity("Points", b =>
                {
                    b.Property<int>("PointsID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PointsID"));

                    b.Property<int>("AutoClickerUpgrades")
                        .HasColumnType("int");

                    b.Property<decimal>("BasePoint")
                        .HasColumnType("decimal(18,2)");

                    b.Property<double>("CriticalBoost")
                        .HasColumnType("float");

                    b.Property<int>("CriticalGainAmount")
                        .HasColumnType("int");

                    b.Property<double>("CriticalGainChance")
                        .HasColumnType("float");

                    b.Property<int>("DelayAmount")
                        .HasColumnType("int");

                    b.Property<decimal>("Overdose")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OverdoseAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("OverdoseUnlocked")
                        .HasColumnType("bit");

                    b.Property<bool>("Pet1")
                        .HasColumnType("bit");

                    b.Property<decimal>("Pet1Boost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("Pet1Equipped")
                        .HasColumnType("bit");

                    b.Property<bool>("Pet2")
                        .HasColumnType("bit");

                    b.Property<decimal>("Pet2Boost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("Pet2Equipped")
                        .HasColumnType("bit");

                    b.Property<bool>("Pet3")
                        .HasColumnType("bit");

                    b.Property<decimal>("Pet3Boost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("Pet3Equipped")
                        .HasColumnType("bit");

                    b.Property<bool>("Pet4")
                        .HasColumnType("bit");

                    b.Property<decimal>("Pet4Boost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("Pet4Equipped")
                        .HasColumnType("bit");

                    b.Property<bool>("Pet5")
                        .HasColumnType("bit");

                    b.Property<decimal>("Pet5Boost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("Pet5Equipped")
                        .HasColumnType("bit");

                    b.Property<int>("PetsEquipped")
                        .HasColumnType("int");

                    b.Property<decimal>("Point")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Prestige")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("PrestigeUnlocked")
                        .HasColumnType("bit");

                    b.Property<decimal>("Upgrade2")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("Upgrade2Unlocked")
                        .HasColumnType("bit");

                    b.Property<decimal>("Upgrade3")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("Upgrade3Unlocked")
                        .HasColumnType("bit");

                    b.Property<decimal>("Upgrade4")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("Upgrade4Unlocked")
                        .HasColumnType("bit");

                    b.Property<decimal>("Upgrade5")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("Upgrade5Unlocked")
                        .HasColumnType("bit");

                    b.Property<decimal>("Upgrades")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("PointsID");

                    b.ToTable("Points");
                });

            modelBuilder.Entity("VenusPoints", b =>
                {
                    b.Property<int>("VenusPointsID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VenusPointsID"));

                    b.Property<int>("AutoDrillBoost")
                        .HasColumnType("int");

                    b.Property<bool>("AutoDrillUnlocked")
                        .HasColumnType("bit");

                    b.Property<decimal>("Crysalline")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Crysallite")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("LaserMinerBoost")
                        .HasColumnType("int");

                    b.Property<bool>("LaserMinerUnlocked")
                        .HasColumnType("bit");

                    b.Property<int>("MineCost")
                        .HasColumnType("int");

                    b.Property<int>("MineLevel")
                        .HasColumnType("int");

                    b.Property<bool>("QuantumExtractorUnlocked")
                        .HasColumnType("bit");

                    b.HasKey("VenusPointsID");

                    b.ToTable("VenusPoints");
                });
#pragma warning restore 612, 618
        }
    }
}
